import type { DetectorContext, DetectorResult } from '../types';

// shadcn/ui generates a very specific set of CSS custom properties in globals.css.
// The combination of --muted-foreground, --destructive, --ring, and --radius
// with HSL value syntax virtually never appears outside shadcn-based projects.
const SHADCN_CSS_VARS = [
  '--muted-foreground',
  '--destructive-foreground',
  '--popover-foreground',
  '--card-foreground',
  '--accent-foreground',
  '--secondary-foreground',
  '--primary-foreground',
];

// tailwindcss-animate (bundled with shadcn) adds these specific animation class names
const TAILWIND_ANIMATE_CLASSES = [
  'animate-in', 'animate-out',
  'fade-in-0', 'fade-out-0',
  'zoom-in-95', 'zoom-out-95',
  'slide-in-from-top', 'slide-in-from-bottom',
  'slide-out-to-top', 'slide-out-to-bottom',
];

// Radix UI v2 adds data-slot attributes to all primitive components
// This is a very specific fingerprint that only appears in shadcn v2+ projects
const RADIX_DATA_SLOT_COMPONENTS = [
  'data-slot="button"',
  'data-slot="card"',
  'data-slot="dialog"',
  'data-slot="input"',
  'data-slot="badge"',
  'data-slot="separator"',
  'data-slot="tooltip"',
];

// cmdk (command menu) — only ever used in shadcn projects
const CMDK_SIGNATURES = ['cmdk-', 'data-cmdk', '[cmdk'];

// Common AI-generated meta signals
const AI_META_GENERATORS = [
  'content="v0',             // Vercel v0.dev
  'generated by v0',
  'created with bolt',       // bolt.new
  'built with lovable',      // lovable.dev
  'built with cursor',       // cursor AI
];

export function detectTechStack(ctx: DetectorContext): DetectorResult {
  const { $, html } = ctx;
  const evidence: string[] = [];
  let score = 0;

  // ── 1. shadcn CSS custom property fingerprint ─────────────────────────────
  const cssContent: string[] = [];
  $('style').each((_, el) => { cssContent.push($(el).html() || ''); });
  const allCss = cssContent.join('\n') + html;

  const shadcnVarsFound = SHADCN_CSS_VARS.filter((v) => allCss.includes(v));
  if (shadcnVarsFound.length >= 3) {
    const pts = shadcnVarsFound.length >= 5 ? 3 : 2;
    score += pts;
    evidence.push(`shadcn/ui CSS variable fingerprint: ${shadcnVarsFound.slice(0, 4).join(', ')} — specific to shadcn/ui design system`);
  }

  // ── 2. tailwindcss-animate class names ────────────────────────────────────
  const animateClasses = TAILWIND_ANIMATE_CLASSES.filter((cls) => html.includes(cls));
  if (animateClasses.length >= 3) {
    score += 2;
    evidence.push(`tailwindcss-animate classes: ${animateClasses.slice(0, 4).join(', ')} — bundled with shadcn/ui, rarely used independently`);
  }

  // ── 3. Radix UI data-slot attributes (shadcn v2) ──────────────────────────
  const dataSlotFound = RADIX_DATA_SLOT_COMPONENTS.filter((sig) => html.includes(sig));
  if (dataSlotFound.length >= 2) {
    score += 2;
    evidence.push(`Radix UI data-slot attributes: ${dataSlotFound.slice(0, 3).join(', ')} — shadcn v2 component fingerprint`);
  }

  // ── 4. cmdk (command menu component — shadcn-specific) ───────────────────
  const hasCmdk = CMDK_SIGNATURES.some((sig) => html.includes(sig));
  if (hasCmdk) {
    score += 1;
    evidence.push('cmdk command palette component detected — exclusively used in shadcn projects');
  }

  // ── 5. AI tool meta attribution ───────────────────────────────────────────
  const metaGenerator = $('meta[name="generator"]').attr('content') || '';
  const metaAttribution = AI_META_GENERATORS.find(
    (sig) => html.toLowerCase().includes(sig.toLowerCase()) ||
             metaGenerator.toLowerCase().includes(sig.toLowerCase()),
  );
  if (metaAttribution) {
    score += 3;
    evidence.push(`AI tool attribution detected in source: "${metaAttribution}"`);
  }

  // ── 6. Vercel deployment + shadcn stack (very strong compound) ────────────
  const hasVercelMeta = html.includes('vercel.com') || html.includes('_vercel') || html.includes('x-vercel');
  if (hasVercelMeta && shadcnVarsFound.length >= 3) {
    score += 1;
    evidence.push('Vercel deployment + shadcn/ui stack — the dominant AI scaffolding combination');
  }

  score = Math.min(8, score);
  const detected = score >= 3;

  return {
    id: 'tech-stack',
    name: 'AI Stack Fingerprint',
    description: 'shadcn/ui CSS variables, tailwindcss-animate classes, or AI tool attribution in source',
    category: 'structural' as const,
    detected,
    severity: score >= 6 ? 'high' : score >= 4 ? 'medium' : detected ? 'low' : 'none',
    score: detected ? score : 0,
    maxScore: 8,
    evidence: detected ? evidence.slice(0, 4) : [],
    recommendation:
      'The shadcn/ui + Tailwind + Vercel stack is the standard AI code generation output. Differentiating with custom design tokens, a unique component library, or a different deployment stack signals intentional architectural decisions.',
  };
}
