import type { RepoFile, CodeDetectedPattern } from '@/types/github';

// Names that suggest static data arrays for sections
const BOILERPLATE_ARRAY_NAMES = [
  'features', 'benefits', 'services', 'testimonials', 'stats', 'pricing',
  'plans', 'faqs', 'steps', 'reasons', 'team', 'products', 'perks',
  'highlights', 'tiers', 'packages', 'items', 'cards', 'tabs', 'links',
  'navItems', 'menuItems',
];

// Pattern: const features = [ ... ] or const FEATURES = [
const ARRAY_CONST_PATTERN = new RegExp(
  `\\bconst\\s+(${BOILERPLATE_ARRAY_NAMES.join('|')})\\s*(?::\\s*[A-Za-z<>\\[\\]]+)?\\s*=\\s*\\[`,
  'gi',
);

// Pattern: export const data = [...] at top of file
const EXPORT_DATA_PATTERN = /export\s+const\s+\w+\s*(?::\s*\w+(?:<[^>]+>)?(?:\[\])?)?s*=\s*\[/gi;

// Detect repeated object shape: objects with same keys in an array
function detectRepeatObjectShape(content: string): number {
  // Find arrays of objects with identical key patterns
  const objectPattern = /\{[^{}]*title[^{}]*description[^{}]*\}/g;
  const matches = content.match(objectPattern) ?? [];
  return matches.length;
}

function analyzeFile(content: string): {
  arrayConsts: string[];
  boilerplateObjects: number;
  exportedData: boolean;
} {
  const arrayConsts: string[] = [];

  let m: RegExpExecArray | null;
  const arrayRe = new RegExp(ARRAY_CONST_PATTERN.source, 'gi');
  while ((m = arrayRe.exec(content)) !== null) {
    arrayConsts.push(m[1].toLowerCase());
  }

  const boilerplateObjects = detectRepeatObjectShape(content);

  const exportedData = EXPORT_DATA_PATTERN.test(content);

  return { arrayConsts, boilerplateObjects, exportedData };
}

export function detectBoilerplateDetection(files: RepoFile[]): CodeDetectedPattern {
  const sourceFiles = files.filter(
    (f) => f.path.endsWith('.ts') || f.path.endsWith('.tsx') ||
           f.path.endsWith('.js') || f.path.endsWith('.jsx'),
  );

  let totalArrayConsts = 0;
  let totalBoilerplateObjects = 0;
  let filesWithExportedData = 0;
  const allArrayNames: string[] = [];
  const affectedFiles: string[] = [];

  for (const file of sourceFiles) {
    const { arrayConsts, boilerplateObjects, exportedData } = analyzeFile(file.content);

    if (arrayConsts.length > 0 || boilerplateObjects >= 3) {
      affectedFiles.push(file.path.split('/').pop()!.replace(/\.(ts|tsx|js|jsx)$/, ''));
      totalArrayConsts += arrayConsts.length;
      allArrayNames.push(...arrayConsts);
    }

    totalBoilerplateObjects += boilerplateObjects;
    if (exportedData) filesWithExportedData++;
  }

  const detected = totalArrayConsts >= 3 || totalBoilerplateObjects >= 6 || filesWithExportedData >= 2;

  if (!detected) {
    return {
      id: 'boilerplate-detection',
      name: 'AI Boilerplate Detection',
      description: 'Static data arrays + map() patterns commonly generated by AI tools for landing page sections',
      detected: false,
      score: 0,
      maxScore: 10,
      evidence: [],
      details: { arrayConsts: 0, boilerplateObjects: 0, filesWithExportedData: 0 },
    };
  }

  const evidence: string[] = [];

  if (totalArrayConsts >= 3) {
    const uniqueNames = [...new Set(allArrayNames)];
    evidence.push(`${totalArrayConsts} static section-data arrays: const ${uniqueNames.slice(0, 5).join(', ')} = [...]`);
  }

  if (totalBoilerplateObjects >= 5) {
    evidence.push(`${totalBoilerplateObjects} boilerplate objects with title/description fields found in data arrays`);
  }

  if (filesWithExportedData >= 2) {
    evidence.push(`${filesWithExportedData} files export static data arrays — common in AI-generated landing pages`);
  }

  if (affectedFiles.length > 0) {
    evidence.push(`Detected in: ${affectedFiles.slice(0, 4).join(', ')}`);
  }

  const score = Math.min(10, Math.round(
    totalArrayConsts * 1.5 + totalBoilerplateObjects * 0.3 + filesWithExportedData,
  ));

  return {
    id: 'boilerplate-detection',
    name: 'AI Boilerplate Detection',
    description: 'Static data arrays + map() patterns commonly generated by AI tools for landing page sections',
    detected: true,
    score,
    maxScore: 10,
    evidence,
    details: { arrayConsts: totalArrayConsts, boilerplateObjects: totalBoilerplateObjects, filesWithExportedData, affectedFiles: affectedFiles.length },
  };
}
